name: 🧠 Auto-generate Signals

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3:00 UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run generate_signals.py
        run: python media-monitor/generate_signals.py

      - name: Commit updated signals
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/risk_signals.csv
          git commit -m "🤖 Auto-update risk_signals.csv [skip ci]" || echo "No changes"
          git push
