name: Update Media and Scenario Signals

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas
          pip install feedparser
          pip install textblob
          python -m textblob.download_corpora
  

      - name: Run RSS parser
        run: python media-monitor/update_articles.py

      - name: Generate scenario signals
        run: python media-monitor/generate_signals.py

      - name: Git diff
        run: |
          git status
          git diff --stat

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/processed_articles.json data/risk_signals.csv
          git diff --cached --quiet && echo "No changes to commit." || git commit -m "Auto-update media + signals [skip ci]"
          git pull --rebase
          git push
