name: 🤖 Update Media & Scenario Signals

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6:00 UTC
  workflow_dispatch:      # Allows manual trigger from GitHub

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: pip install pandas feedparser

      - name: 📡 Step 1: Run RSS feed parser (update_articles.py)
        run: python media-monitor/update_articles.py

      - name: 🧠 Step 2: Generate scenario signals (generate_signals.py)
        run: python media-monitor/generate_signals.py

      - name: 🕵️ Git diff
        run: |
          git status
          git diff --stat

      - name: 💾 Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/processed_articles.json data/risk_signals.csv
          git diff --cached --quiet && echo "🟢 No changes to commit." || git commit -m "🤖 Auto-update media + signals [skip ci]"
          git push
